version: '3.8'

services:
  # ???? ???? ??????
  postgres:
    image: postgres:16-alpine
    container_name: ticket_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ticketdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ???? ??????? ?????????
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ticket_mq
    ports:
      - "15672:15672" # ??? ???-????????? (???????)
      - "5672:5672"   # ??? ???? ??? ??????? ???? ? ????????

volumes:
  postgres_data: